import Navbar from '@components/navBar'
import { Inter } from 'next/font/google'
import './globals.css';
// import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ['greek'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Navbar />{children}</body>
    </html>
  )
}
